# Site settings
baseurl = "/"
relativeURLs = true
uglyURLs = true
languageCode = "en"
title = "Mengchen Yang"
theme = "hugo-theme-cactus-plus"
googleAnalytics = "UA-155127085-1"
# Set the value to true if your site include CJK (Chinese, Japanese, and Korean languages) characters
hasCJKLanguage = false

[params]
	author = "Mengchen Yang"
	description = "Mengchen"
	bio = "Connect people, technology and community together"

	twitter = ""
	facebook = ""
	GitHub = "mengchenyang"

	enableRSS = false
	enableToc = true

	enableDisqus = false
	disqusShortname = "your_disqus_short_name"


	enableSummary = true
	# Set the value to true if use description in post front matter replace content summary
	useDescriptionReplaceSummary = true


	enableGoogleAnalytics = true
	enableBaiduAnalytics = false
	# Set the value to your baidu analysis code if you want to use baidu analytics
	baiduAnalytics = 'your_baidu_analysis_code'

	enableTwitterCard = false
	# The url for twitter card image, default is avatar.png in static/images directory
	twitterCardImage = ""

	# Add custom assets with their paths relative to the static folder
	customCSS = []
	customJS  = []

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = ""
	about = ""
	archive = ""


	olderPosts = ""
	newerPosts = ""
	copyright = ""

	# show latest posts in single page
	showLatestPosts = false
	readMore = ""

	# Share
	enableShare = true
	tweet = ""
	share = ""

	# 404 page
	title404 = ""
	subtitle404 = ""

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "font-awesome"
  # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
  socialIconStyle = ""


# Add additional social link entries underneath
[social]
	github-square = "https://www.github.com/mengchenyang"
	Linkedin-square = "https://www.linkedin.com/in/mengchen-yang-93533910b/"
	Twitter-square = "https://twitter.com/947887815"
